export const MIN_GAMES_FOR_INCLUSION = 4;

export const MIN_CORRELATION_SAMPLE = 12;
export const MIN_PEER_SAMPLE = 8;
export const MIN_PEAK_WINDOW_SAMPLE = 8;

export const HIGH_CONFIDENCE_PEER_SAMPLE = 20;
export const MEDIUM_CONFIDENCE_PEER_SAMPLE = 12;

export const AGE_CURVE_SMOOTHING_RADIUS = 1;

export const AHEAD_OF_CURVE_DELTA_THRESHOLD = 0.12;
export const BEHIND_CURVE_DELTA_THRESHOLD = -0.12;
export const ANOMALY_DELTA_THRESHOLD = 0.3;
